export type AiGenreId =
  | 'research'
  | 'writing'
  | 'coding'
  | 'analysis'
  | 'agent'
  | 'textImage'
  | 'imageImage'
  | 'textVideo'
  | 'imageVideo'

export type AiGenre = {
  id: AiGenreId
  label: string
  shortLabel: string
  description: string
  primaryMetrics: string[]
  sourceMetric: string
}

export type AiModel = {
  id: string
  name: string
  creator: string
  family: string
  releaseLabel: string
  modality: 'LLM' | 'Image' | 'Video'
  accessType: 'Proprietary' | 'Open weights' | 'Specialized'
  costLevel: 1 | 2 | 3 | 4 | 5
  speed: number
  japanese: number
  context: number
  visibleIn: AiGenreId[]
  performance: Record<AiGenreId, number>
  costPerformance: Record<AiGenreId, number>
  strengths: string[]
  cautions: string[]
  bestFor: string
  avoidFor: string
  note: string
  rank?: number
  metric?: string
  priceLabel?: string
  sourceUrl?: string
}

export type AiModelComparePayload = {
  models: AiModel[]
  updatedAt: string
  source: 'live' | 'fallback'
  sourceLabel: string
  sourceUrl: string
  isLive: boolean
  message: string
}

export const AI_GENRES: AiGenre[] = [
  {
    id: 'research',
    label: 'リサーチ・情報整理',
    shortLabel: 'リサーチ',
    description:
      '情報収集、出典確認、比較検討、長い資料の整理に向くLLMを比較します。',
    primaryMetrics: ['推論力', '長文読解', '出典確認', '情報整理'],
    sourceMetric: '公開ベンチマーク、速度、価格、文脈長、用途適性を項目別に確認します。',
  },
  {
    id: 'writing',
    label: '文章作成・記事改善',
    shortLabel: '文章',
    description:
      '記事作成、リライト、構成整理、トーン調整に向くLLMを比較します。',
    primaryMetrics: ['推論力', '指示追従', '長文編集', '日本語運用'],
    sourceMetric: '文章品質、長文処理、指示追従、料金バランスを項目別に確認します。',
  },
  {
    id: 'coding',
    label: 'コード・開発補助',
    shortLabel: 'コード',
    description:
      '実装、デバッグ、設計相談、既存コード読解に向くLLMを比較します。',
    primaryMetrics: ['Coding Index', '実装力', 'デバッグ', '設計相談'],
    sourceMetric: 'コード系ベンチマーク、推論力、価格、実装補助の相性を項目別に確認します。',
  },
  {
    id: 'analysis',
    label: 'データ分析・表計算',
    shortLabel: '分析',
    description:
      '数値処理、表計算、グラフ化、業務データ整理に向くLLMを比較します。',
    primaryMetrics: ['Math Index', '数値処理', '表計算', '推論力'],
    sourceMetric: '数理・分析系ベンチマーク、推論力、表計算やデータ整理の相性を項目別に確認します。',
  },
  {
    id: 'agent',
    label: 'エージェント性能',
    shortLabel: 'エージェント',
    description:
      'ツール実行、複数ステップの作業、長時間の自律タスクに向くLLMを比較します。',
    primaryMetrics: ['Agentic Index', 'ツール利用', '長時間タスク', '指示追従'],
    sourceMetric:
      'エージェント系ベンチマーク、コード理解、長時間タスク適性、ツール利用のしやすさを項目別に確認します。',
  },
  {
    id: 'textImage',
    label: '画像生成（Text to Image）',
    shortLabel: 'Text→Image',
    description:
      'テキストプロンプトから画像を生成するモデルを比較します。',
    primaryMetrics: ['Text to Image Elo', '画質', '指示追従', '商用運用'],
    sourceMetric: '画像生成の公開評価、価格、用途適性、商用利用時の確認しやすさを項目別に確認します。',
  },
  {
    id: 'imageImage',
    label: '画像編集（Image Editing）',
    shortLabel: 'Image→Image',
    description:
      '画像をもとに編集やバリエーション生成を行うモデルを比較します。',
    primaryMetrics: ['Image Editing Elo', '画質', '指示追従', '商用運用'],
    sourceMetric: '画像編集の公開評価、価格、用途適性、商用利用時の確認しやすさを項目別に確認します。',
  },
  {
    id: 'textVideo',
    label: '動画生成（Text to Video）',
    shortLabel: 'Text→Video',
    description:
      'テキストプロンプトだけから動画を生成するモデルを比較します。',
    primaryMetrics: ['Text to Video Elo', '映像品質', '動き', '素材化'],
    sourceMetric: '動画生成の公開評価、価格、生成品質、制作ワークフローへの組み込みやすさを項目別に確認します。',
  },
  {
    id: 'imageVideo',
    label: '動画生成（Image to Video）',
    shortLabel: 'Image→Video',
    description:
      '参照画像をもとに動画を生成するモデルを比較します。',
    primaryMetrics: ['Image to Video Elo', '映像品質', '動き', '素材化'],
    sourceMetric: 'Image to Videoの公開評価、価格、動きの自然さ、素材制作での扱いやすさを項目別に確認します。',
  },
]

const ZERO_PERFORMANCE: Record<AiGenreId, number> = {
  research: 0,
  writing: 0,
  coding: 0,
  analysis: 0,
  agent: 0,
  textImage: 0,
  imageImage: 0,
  textVideo: 0,
  imageVideo: 0,
}

function scores(values: Partial<Record<AiGenreId, number>>): Record<AiGenreId, number> {
  return { ...ZERO_PERFORMANCE, ...values }
}

export const FALLBACK_UPDATED_AT = '2026-05-06T00:00:00.000+09:00'

export const FALLBACK_AI_MODELS: AiModel[] = [
  {
    id: 'gpt-5-5-xhigh',
    name: 'GPT-5.5 (xhigh)',
    creator: 'OpenAI',
    family: 'GPT',
    releaseLabel: 'LLM',
    modality: 'LLM',
    accessType: 'Proprietary',
    costLevel: 5,
    speed: 73,
    japanese: 92,
    context: 92,
    visibleIn: ['research', 'writing', 'coding', 'analysis', 'agent'],
    rank: 1,
    metric: 'Intelligence Index 60',
    priceLabel: '$11.25 / 1M tokens',
    sourceUrl: 'https://artificialanalysis.ai/leaderboards/models',
    performance: scores({ research: 100, writing: 100, coding: 96, analysis: 96, agent: 98 }),
    costPerformance: scores({ research: 67, writing: 67, coding: 65, analysis: 65, agent: 66 }),
    strengths: ['総合推論が非常に強い', 'コード、分析、複雑な設計相談に向く', '難しい指示を粘り強く処理しやすい'],
    cautions: ['高コストで待ち時間も長め', '軽い要約や分類には過剰になりやすい'],
    bestFor: '難しい分析、コード、設計、記事改善の最終判断まで任せたい人。',
    avoidFor: '低コストで大量処理したい用途。',
    note: '公開ベンチマークと料金情報をもとにした初期評価データです。',
  },
  {
    id: 'gpt-5-5-high',
    name: 'GPT-5.5 (high)',
    creator: 'OpenAI',
    family: 'GPT',
    releaseLabel: 'LLM',
    modality: 'LLM',
    accessType: 'Proprietary',
    costLevel: 5,
    speed: 71,
    japanese: 92,
    context: 92,
    visibleIn: ['research', 'writing', 'coding', 'analysis', 'agent'],
    rank: 2,
    metric: 'Intelligence Index 59',
    priceLabel: '$11.25 / 1M tokens',
    sourceUrl: 'https://artificialanalysis.ai/leaderboards/models',
    performance: scores({ research: 98, writing: 98, coding: 95, analysis: 95, agent: 96 }),
    costPerformance: scores({ research: 66, writing: 66, coding: 64, analysis: 64, agent: 65 }),
    strengths: ['xhighより扱いやすく高性能', '文章、コード、分析を横断しやすい', '汎用の上位比較軸にしやすい'],
    cautions: ['価格は高め', '速度だけなら軽量モデルも比較したい'],
    bestFor: '高性能を保ちつつ、xhighほど重くしたくない人。',
    avoidFor: '日常の軽作業だけを高速に回したい人。',
    note: '高性能LLMの比較基準です。',
  },
  {
    id: 'claude-opus-4-7-max',
    name: 'Claude Opus 4.7 (max)',
    creator: 'Anthropic',
    family: 'Claude Opus',
    releaseLabel: 'LLM',
    modality: 'LLM',
    accessType: 'Proprietary',
    costLevel: 4,
    speed: 47,
    japanese: 94,
    context: 95,
    visibleIn: ['research', 'writing', 'coding', 'analysis', 'agent'],
    rank: 3,
    metric: 'Intelligence Index 57',
    priceLabel: '$10.94 / 1M tokens',
    sourceUrl: 'https://artificialanalysis.ai/leaderboards/models',
    performance: scores({ research: 95, writing: 95, coding: 94, analysis: 90, agent: 94 }),
    costPerformance: scores({ research: 65, writing: 65, coding: 64, analysis: 62, agent: 64 }),
    strengths: ['文章編集と長文読解に強い', '複雑な指示を保ちやすい', 'コードやエージェント用途でも上位候補'],
    cautions: ['速度は速度重視ではない', '画像や動画生成は別ツールが必要'],
    bestFor: '長文記事、リライト、慎重な調査整理、コード相談。',
    avoidFor: '動画や画像生成まで1つで済ませたい人。',
    note: '文章品質を重視する比較で外しにくいモデルです。',
  },
  {
    id: 'gemini-3-1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    creator: 'Google',
    family: 'Gemini',
    releaseLabel: 'LLM',
    modality: 'LLM',
    accessType: 'Proprietary',
    costLevel: 3,
    speed: 137,
    japanese: 88,
    context: 98,
    visibleIn: ['research', 'writing', 'coding', 'analysis', 'agent'],
    rank: 4,
    metric: 'Intelligence Index 57',
    priceLabel: '$4.50 / 1M tokens',
    sourceUrl: 'https://artificialanalysis.ai/leaderboards/models',
    performance: scores({ research: 95, writing: 95, coding: 91, analysis: 92, agent: 93 }),
    costPerformance: scores({ research: 82, writing: 82, coding: 80, analysis: 80, agent: 81 }),
    strengths: ['長文とリサーチに強い', '速度と価格のバランスがよい', 'Google系の作業導線と相性がよい'],
    cautions: ['Preview系は仕様が変わる可能性がある', '日本語の最終仕上げは好みが分かれる'],
    bestFor: 'リサーチ、資料整理、長文読解、Google環境中心의作業。',
    avoidFor: '安定した本番運用だけを重視する用途。',
    note: '長文・調査寄りの強力な候補です。',
  },
  {
    id: 'kimi-k2-6',
    name: 'Kimi K2.6',
    creator: 'Kimi',
    family: 'Kimi',
    releaseLabel: 'LLM',
    modality: 'LLM',
    accessType: 'Proprietary',
    costLevel: 2,
    speed: 34,
    japanese: 74,
    context: 86,
    visibleIn: ['research', 'writing', 'coding', 'analysis', 'agent'],
    rank: 6,
    metric: 'Intelligence Index 54',
    priceLabel: '$1.71 / 1M tokens',
    sourceUrl: 'https://artificialanalysis.ai/leaderboards/models',
    performance: scores({ research: 90, writing: 90, coding: 86, analysis: 84, agent: 86 }),
    costPerformance: scores({ research: 87, writing: 87, coding: 84, analysis: 83, agent: 84 }),
    strengths: ['性能に対して価格を抑えやすい', 'コードと分析の補助に向く', '上位勢との比較軸になる'],
    cautions: ['日本語記事の仕上げは確認したい', '一般ユーザー向けUIは別途確認が必要'],
    bestFor: 'コストと性能のバランスを重視する開発者。',
    avoidFor: '日本語記事の最終品質だけを重視する人。',
    note: 'コスパ比較で入れておきたいモデルです。',
  },
  {
    id: 'flux-1-pro',
    name: 'FLUX.1 [pro]',
    creator: 'Black Forest Labs',
    family: 'FLUX',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Specialized',
    costLevel: 4,
    speed: 55,
    japanese: 75,
    context: 40,
    visibleIn: ['textImage'],
    rank: 1,
    metric: 'Text to Image Elo 1358',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 100 }),
    costPerformance: scores({ textImage: 78 }),
    strengths: ['写真のようにリアルな極限のディテール表現', '複雑なプロンプトへの正確な追従', '画像内のテキスト描画が極めて正確'],
    cautions: ['生成単価が比較的高め', '実在商品風の表現は権利面に注意が必要'],
    bestFor: '広告クリエイティブ、極限のフォトリアル画像、テキストを含むグラフィック生成。',
    avoidFor: '低コストで何千枚も大量生成したい用途。',
    note: 'Text-to-Imageリーダーボードで圧倒的な頂点に君臨するプロ向けモデルです。',
  },
  {
    id: 'imagen-3',
    name: 'Imagen 3',
    creator: 'Google',
    family: 'Imagen',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Specialized',
    costLevel: 3,
    speed: 68,
    japanese: 78,
    context: 40,
    visibleIn: ['textImage'],
    rank: 2,
    metric: 'Text to Image Elo 1324',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 98 }),
    costPerformance: scores({ textImage: 85 }),
    strengths: ['非常に高い画質と自然なテキスト描画能力', 'Google製品（Gemini等）にシームレス統合', '幅広いスタイルとアスペクト比対応'],
    cautions: ['表現規制がやや厳格な傾向がある', 'ローカル実行は不可能'],
    bestFor: 'Gemini環境でのデザイン制作、バナー作成、テキストを含む高品質イラスト。',
    avoidFor: '自由度の極めて高いセンシティブ・エッジの効いた表現。',
    note: 'Googleの最高峰画像生成モデルで、優れたバランスを誇ります。',
  },
  {
    id: 'flux-1-dev',
    name: 'FLUX.1 [dev]',
    creator: 'Black Forest Labs',
    family: 'FLUX',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Open weights',
    costLevel: 3,
    speed: 58,
    japanese: 72,
    context: 40,
    visibleIn: ['textImage'],
    rank: 3,
    metric: 'Text to Image Elo 1320',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 96 }),
    costPerformance: scores({ textImage: 88 }),
    strengths: ['pro版に肉薄する驚異的なハイクオリティ画質', 'オープンウェイトでローカル動作も可能', '優れたディテールとリアルな質感'],
    cautions: ['商用利用には追加条件やAPI経由が必要', '高いGPUスペックが要求される'],
    bestFor: 'ローカルでの精緻なデザイン生成、クオリティを極めた画像生成。',
    avoidFor: '超低スペックPCでのローカル実行。',
    note: 'オープンウェイトモデルの常識を覆す最高峰のFLUX中位モデルです。',
  },
  {
    id: 'midjourney-v6',
    name: 'Midjourney v6',
    creator: 'Midjourney',
    family: 'Midjourney',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Proprietary',
    costLevel: 3,
    speed: 60,
    japanese: 80,
    context: 45,
    visibleIn: ['textImage'],
    rank: 4,
    metric: 'Text to Image Elo 1318',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 97 }),
    costPerformance: scores({ textImage: 82 }),
    strengths: ['他を圧倒する圧倒的芸術性と映画的な画質', '強力なスタイル・トーン調整機能', '人物・背景表現で世界最強クラスの美学'],
    cautions: ['公式開発者APIが未提供で、基本はDiscord/Web UI利用', 'プロンプト文字描画はFLUXより一歩譲る'],
    bestFor: '映画的グラフィック、コンセプトアート、極上のイラスト制作。',
    avoidFor: 'APIによるシステム自動生成ワークフロー。',
    note: 'アーティストから絶大な支持を得る最高峰の表現特化モデルです。',
  },
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    creator: 'OpenAI',
    family: 'DALL-E',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Proprietary',
    costLevel: 4,
    speed: 62,
    japanese: 85,
    context: 40,
    visibleIn: ['textImage'],
    rank: 5,
    metric: 'Text to Image Elo 1288',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 92 }),
    costPerformance: scores({ textImage: 80 }),
    strengths: ['抜群のプロンプト理解力と高度な構成力', 'ChatGPT Plusで対話しつつ生成できる圧倒的利便性', 'イラストや構図の整合性が非常に高い'],
    cautions: ['フォトリアル（写真らしさ）はFLUXやMidjourneyに一歩譲る', '生成コストがやや高め'],
    bestFor: 'ChatGPTを使った対話型画像作成、キャラクターデザイン、構図の細かな指示。',
    avoidFor: '極限までリアルな写真調の人物・背景生成。',
    note: 'プロンプトを最も忠実に再現するOpenAIの強力なモデルです。',
  },
  {
    id: 'stable-diffusion-3-5-large',
    name: 'Stable Diffusion 3.5 Large',
    creator: 'Stability AI',
    family: 'Stable Diffusion',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Open weights',
    costLevel: 3,
    speed: 55,
    japanese: 65,
    context: 35,
    visibleIn: ['textImage'],
    rank: 6,
    metric: 'Text to Image Elo 1255',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 88 }),
    costPerformance: scores({ textImage: 76 }),
    strengths: ['オープンライセンスで高度な追加学習やローカルカスタマイズが可能', 'ControlNet等での緻密な構図制御と高相性', '解像度とカスタマイズ性の高さ'],
    cautions: ['デフォルト状態の人物ポーズや解剖学的破綻が稀に発生する', 'プロンプトのみでの制御はFLUXに劣る場合がある'],
    bestFor: '独自の学習モデル（LoRA等）を使ったキャラクター生成、ポーズ制御デザイン。',
    avoidFor: 'プロンプト入力だけで一発で完璧な画像を期待したい初心者。',
    note: 'カスタマイズとローカル環境で強みを発揮する定番モデルの最新世代です。',
  },
  {
    id: 'flux-1-schnell',
    name: 'FLUX.1 [schnell]',
    creator: 'Black Forest Labs',
    family: 'FLUX',
    releaseLabel: 'Text to Image',
    modality: 'Image',
    accessType: 'Open weights',
    costLevel: 1,
    speed: 95,
    japanese: 70,
    context: 40,
    visibleIn: ['textImage'],
    rank: 7,
    metric: 'Text to Image Elo 1240',
    sourceUrl: 'https://artificialanalysis.ai/image/leaderboard/text-to-image',
    performance: scores({ textImage: 86 }),
    costPerformance: scores({ textImage: 98 }),
    strengths: ['驚異的な生成スピード（1-4ステップで超高速生成）', '極めて安価なAPI単価（圧倒的低コスト）', '高速ながら高いテキスト描画力'],
    cautions: ['極めて緻密な光の表現や複雑な芸術性は上位版に劣る', '生成ステップが少ないため調整にコツが要る'],
    bestFor: 'チャット中のリアルタイム生成、大量の画像プロトタイプ作成、低予算デザイン。',
    avoidFor: '最高品質のポスターや高解像度のアート素材。',
    note: '圧倒的な処理速度と低コストで実用性を極めたFLUXの高速モデルです。',
  },
  {
    id: 'sora-text-video',
    name: 'Sora',
    creator: 'OpenAI',
    family: 'Sora',
    releaseLabel: 'Text to Video',
    modality: 'Video',
    accessType: 'Proprietary',
    costLevel: 5,
    speed: 40,
    japanese: 45,
    context: 35,
    visibleIn: ['textVideo'],
    rank: 1,
    metric: 'Text to Video Elo 1350',
    sourceUrl: 'https://artificialanalysis.ai/video/leaderboard/text-to-video',
    performance: scores({ textVideo: 100 }),
    costPerformance: scores({ textVideo: 65 }),
    strengths: ['現実的な物理法則シミュレーション能力', '最長60秒の映画級動画生成', '一貫したカメラワークと破綻のない移動'],
    cautions: ['生成コストが極めて高い', '一般解放の枠や待機時間が長め'],
    bestFor: '長尺のシネマティック映像、映画予告風のBロール、高度な物理シミュレーション。',
    avoidFor: '低コストで手軽に動画を量産したい用途。',
    note: '動画生成AIの概念を塗り替えたOpenAI of 最高峰フラッグシップモデルです。',
  },
  {
    id: 'kling-3-0-pro',
    name: 'Kling 3.0 (Pro)',
    creator: 'KlingAI',
    family: 'Kling',
    releaseLabel: 'Text to Video',
    modality: 'Video',
    accessType: 'Specialized',
    costLevel: 4,
    speed: 52,
    japanese: 40,
    context: 32,
    visibleIn: ['textVideo'],
    rank: 2,
    metric: 'Text to Video Elo 1295',
    sourceUrl: 'https://artificialanalysis.ai/video/leaderboard/text-to-video',
    performance: scores({ textVideo: 96 }),
    costPerformance: scores({ textVideo: 85 }),
    strengths: ['人物の自然な動きと豊かな表情変化', '複雑なカメラ制御（ズーム・トラッキング等）', '極めて高い映像解像度と光沢感'],
    cautions: ['一部の激しい動きで物理的な破綻が発生することがある'],
    bestFor: 'キャラクター動画、表情を重視するSNS動画、短尺プロモーション映像。',
    avoidFor: '静止画に近い単純なカメラスライドのみの低コスト動画。',
    note: '業界でも屈指の品質と操作性を兼ね備えた最新の動画生成モデルです。',
  },
  {
    id: 'runway-gen-3-alpha',
    name: 'Runway Gen-3 Alpha',
    creator: 'Runway',
    family: 'Runway',
    releaseLabel: 'Text to Video',
    modality: 'Video',
    accessType: 'Specialized',
    costLevel: 4,
    speed: 48,
    japanese: 42,
    context: 32,
    visibleIn: ['textVideo'],
    rank: 3,
    metric: 'Text to Video Elo 1265',
    sourceUrl: 'https://artificialanalysis.ai/video/leaderboard/text-to-video',
    performance: scores({ textVideo: 92 }),
    costPerformance: scores({ textVideo: 78 }),
    strengths: ['プロの映像制作ワークフローに標準統合', 'カメラモーションと時間的一貫性の高さ', '高度なディレクター制御ブラシ'],
    cautions: ['プラン消費（クレジット）が極めて早い', '文字の描画は限定的'],
    bestFor: 'プロ用のポストプロダクション、映像ディレクション、高品質クリエイティブ制作。',
    avoidFor: '動画生成をとりあえず無料やお試し感覚で使いたい人。',
    note: '映像業界のプロフェッショナルが実務で活用する標準的動画生成モデルです。',
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    creator: 'Luma AI',
    family: 'Luma',
    releaseLabel: 'Text to Video',
    modality: 'Video',
    accessType: 'Specialized',
    costLevel: 3,
    speed: 55,
    japanese: 38,
    context: 30,
    visibleIn: ['textVideo'],
    rank: 4,
    metric: 'Text to Video Elo 1238',
    sourceUrl: 'https://artificialanalysis.ai/video/leaderboard/text-to-video',
    performance: scores({ textVideo: 88 }),
    costPerformance: scores({ textVideo: 84 }),
    strengths: ['3D空間の整合性が非常に高く破綻しにくい', 'ダイナミックでスピーディーなカメラアングル', '生成時間が比較的短い'],
    cautions: ['キャラクターの顔が一貫性を失うことがある'],
    bestFor: '臨場感のある一人称視点動画、アクションカメラアングル、すばやいシーン構築。',
    avoidFor: '表情の非常に細やかな機微をメインにする動画。',
    note: '3Dスキャンに強みを持つLumaが開発した、空間再現性の高い動画生成モデルです。',
  },
  {
    id: 'veo-3-0',
    name: 'Veo 3.0',
    creator: 'Google',
    family: 'Veo',
    releaseLabel: 'Image to Video',
    modality: 'Video',
    accessType: 'Specialized',
    costLevel: 4,
    speed: 46,
    japanese: 42,
    context: 32,
    visibleIn: ['imageVideo'],
    rank: 1,
    metric: 'Image to Video Elo 1280',
    sourceUrl: 'https://artificialanalysis.ai/video/leaderboard/image-to-video',
    performance: scores({ imageVideo: 94 }),
    costPerformance: scores({ imageVideo: 82 }),
    strengths: ['高解像度1080pシネマティック映像品質', '画像からの精緻な動きの誘導能力（最強格のI2V）', 'Google製品やYouTubeツールへのシームレスな統合'],
    cautions: ['一般向けの直接利用プランが限られる場合がある', '厳格なセーフティチェックによる表現制限'],
    bestFor: '元の静止画イラストのイメージを完璧に維持したまま動画化する用途。',
    avoidFor: '完全に自由度の高いアングルの指示や激しいファンタジー効果。',
    note: 'Googleが誇る、静止画からのアニメーション生成能力に優れた動画モデルです。',
  },
]

export const FALLBACK_AI_PAYLOAD: AiModelComparePayload = {
  models: FALLBACK_AI_MODELS,
  updatedAt: FALLBACK_UPDATED_AT,
  source: 'fallback',
  sourceLabel: '公開ベンチマーク・料金情報・公式情報',
  sourceUrl: '/about',
  isLive: false,
  message:
    '現在は公開ベンチマーク、料金情報、公式情報をもとにしたAincarn編集データを表示しています。独自実測データは順次追加します。',
}
